### ISSUE TITLE
Nested cross val for Hyperparameter tuning

### ISSUE THREAD

**Issue by herbzhao** [vecxoz/vecstack#11]
Vecstack, as many people have pointed out, is fitting in a nice niche that solve a complex problem in single line of code. 

I am aware of that stacking is very similar to cross-validation as it works with k-fold and oof. I wonder how does it work with hyperparameter tuning, e.g. gridsearchCV or Randomizedsearch? 

Would you suggest us to hypertune the model before constructing them as the level 1 models for stacking? or this can be done together.

**Comment by vecxoz** [comment]
Thanks for this important question!

`StackingTransformer` behaves like any sklearn-like transformer but due to nature of stacking it contains CV inside. So technically we can create pipeline (e.g. `StackingTransformer` + 2nd level estimator) and tune all parameters using `(Randomized)GridSearchCV`. But this is **very computationally intensive** task because here we deal with **nested CV**: for each fold of grid search - stacking procedure performs all its own (nested) folds. 

Moreover, `(Randomized)GridSearchCV` **refit all transformers in pipeline for each parameter combination**, even if we want to tune only parameters of final estimator. It means that `StackingTransformer` will be forced to recompute stacked features (i.e. rerun all folds with all 1st level estimators) for each parameter combination even if we want to tune only 2nd level estimator.

Conclusion.
Although tuning the whole stacking pipeline with `(Randomized)GridSearchCV` may be useful for some research purposes it is **not recommended** for practice. General practical advice is to **tune each estimator separately** and then use tuned estimators on the 1st level of stacking. Higher level estimators should be tuned in the same fashion using stacked features from previous level. For manual tuning you can use `stacking` function or `StackingTransformer` with a single 1st level estimator.
