### ISSUE TITLE
Ability to use different features in each model.

### ISSUE THREAD

**Issue by nathanwalker-sp** [vecxoz/vecstack#49]
I have a model whose most predictive features are the most noisy. To compensate, I train 1 model on those features, and a separate model on all the other features. By combining these models, I can quickly and easily prevent strange outlier predictions.

Simple stacking / voting is okay, but I imagine the model would generalize better were I to implement vecstack instead.
Is there any feasible way we could add different X (column-wise) *per* model to vecstack? I.e. multiple X that are the same length, but have different widths.

Thank you for your time!
-Nathan

**Comment by vecxoz** [comment]
Within each single run of vecstack all models expect uniform feature set. So there is no way to pass different X per model. But in fact there is no need to do it in a single run. 

In order to use different sets of features you can perform several runs on the 1st level passing corresponding X and finally you can combine all results on the 2nd level. Please see code example in this [post]( https://github.com/vecxoz/vecstack/issues/8#issuecomment-369256895) (after the sentence “We might want to use different data scaling and preprocessing techniques for different algorithms…”)

**Comment by nathanwalker-sp** [comment]
@vecxoz Thank you for this explanation, this is very helpful!

In my use case, it sounds like I could get the intended result by just feeding 1 model to each `vecstack.stacking()`?

I.e, 

```
X_train_1 = df[some_features]
X_train_2 = df[other_features]

models_1 = [LinearRegression] # is this right?
S_train_1, S_test_1 = stacking(models_1, X_train_1, y_train, X_test_1)

models_2 = [LinearRegression] # is this right?
S_train_2, S_test_2 = stacking(models_2, X_train_2, y_train, X_test_2)
```

and then just use `S_train_1` and `S_train_2` as the features for a 'final' estimator since the cv folds from the 2 stacking procedures should be identical?

**Comment by vecxoz** [comment]
Everything is correct except initialization. Don’t forget parentheses:

`models_1 = [LinearRegression()]`

**Comment by nathanwalker-sp** [comment]
Perfect, thanks! :)
