### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by jrzaurin** [vecxoz/vecstack#5]
Hi there

nice package. Just a quick one, in line 409 at `core.py` there is:

    X_train = np.array(X_train)
    y_train = np.array(y_train).ravel()
    X_test = np.array(X_test)

I am not sure that is necessary?  For example using sparse matrices this return an array with the sparse matrix "inside" (i.e. no shape) rather than an array `THAT IS` the sparse matrix. This will throw an error at line 502:

     IndexError: tuple index out of range

as 

     In [31]: X_train.shape
     Out[31]: ()

I am at the moment running it just commenting out those lines with no problem.

Just that, maybe considering commenting out the lines or add an `if` statement for sparse matrices?

Thanks

**Comment by vecxoz** [comment]
**Thanks a lot! Nice catch!**

At this point in code we must check arrays, because unexpected array types may give very strange errors later. So I followed scikit-learn recommendation and used functions [check_X_y](http://scikit-learn.org/stable/modules/generated/sklearn.utils.check_X_y.html) and [check_array](http://scikit-learn.org/stable/modules/generated/sklearn.utils.check_array.html) as follows:

```python
from sklearn.utils.validation import check_X_y, check_array

X_train, y_train = check_X_y(X_train,
                             y_train,
                             accept_sparse=True, # allow all types of sparse
                             force_all_finite=False, # allow nan and inf because 
                                                     # some models (xgboost) can handle
                             multi_output=False) # do not allow several columns in y_train
                             
if X_test is not None: # allow X_test to be None for mode='oof'
    X_test = check_array(X_test,
                         accept_sparse=True, # allow all types of sparse
                         force_all_finite=False) # allow nan and inf because 
                                                 # some models (xgboost) can handle
```
I’ve just **fixed** the issue. Please look at this [commit](https://github.com/vecxoz/vecstack/commit/39fae2763c1eea29258c893b3617469168a07765).

You can reinstall package from github directly (without git and without updating dependencies):
`pip install --upgrade --no-deps https://github.com/vecxoz/vecstack/archive/master.zip`

Thanks again! Please report if you find anything strange.

**Comment by vecxoz** [comment]
Related note.

In 0.2.2 release I finally used `accept_sparse=['csr']` instead of `accept_sparse=True`.
`accept_sparse=['csr']` means that we allow CSR and transform all other sparse types to CSR.
This approach is more consistent because some sparse types e.g. COO are not subscriptable (so we can't make CV split directly) but allow transformation to CSR.
