### ISSUE TITLE
Is vecstack still alive?

### ISSUE THREAD

**Issue by zachmayer** [vecxoz/vecstack#51]
I note that the:
- release is 0.4.0 
- [last commit](https://github.com/vecxoz/vecstack/commits/master/) was 5 years ago
- python badge is 3.5 | 3.6 | 3.7, all of which are end-of-life

Does this mean vecstack will stop working at some point in the near future?

Or is vecstack complete and stable, with no issues on the horizon?

Either way, I'd be happy to help out with any needed maintenance: I love this package!

**Comment by vecxoz** [comment]
Hi @zachmayer,

Thanks a lot for using and enjoying `vecstack`!

It is stable and fully functional with all recent Python versions. I just skipped cosmetic updates for some time, but I keep an eye on critical issues. Currently only the test suite requires real maintenance which I plan to do in the near future. Some tests do not pass during builds due to problems in tests themselves, not the main codebase.

**Comment by zachmayer** [comment]
@vecxoz that's good to hear! Thank you!
